require 'buildr/scala'

# Generated by Buildr 1.4.4, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "frogfish-scala"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
#repositories.remote << "http://www.ibiblio.org/maven2/"
repositories.remote << "http://repo1.maven.org/maven2/"

module Frogfish
  COMPILE_LIBRARIES = []
  COMPILE_LIBRARIES << 'javax.jms:jms:jar:1.1'
  COMPILE_LIBRARIES << 'com.espertech:esper:jar:4.0.0'
  COMPILE_LIBRARIES << 'org.codehaus.jackson:jackson-core-asl:jar:1.6.3'
  COMPILE_LIBRARIES << 'org.codehaus.jackson:jackson-mapper-asl:jar:1.6.3'
  COMPILE_LIBRARIES << 'org.apache.activemq:activemq-all:jar:5.4.2'
  COMPILE_LIBRARIES << 'commons-lang:commons-lang:jar:2.5'
  COMPILE_LIBRARIES << 'commons-logging:commons-logging:jar:1.1.1'

  RUN_LIBRARIES = COMPILE_LIBRARIES.dup
end

desc "The Frogfish-scala project"
define "frogfish-scala" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  Frogfish::COMPILE_LIBRARIES.each { |x| compile.with x }
  Frogfish::RUN_LIBRARIES.each { |x| run.with x }
  package :jar
end
